services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        networks:
            - laravel_network
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db

    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        container_name: node_app
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        networks:
            - laravel_network

    webserver:
        image: nginx:stable-alpine
        container_name: nginx_server
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    dbdata:
        driver: local
